# Generated by Django 3.1.7 on 2022-03-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('L', 'LEFT'), ('R', 'RIGHT'), ('D', 'DOWN'), ('U', 'UP')], max_length=100)),
                ('distance', models.IntegerField()),
                ('destinationPointId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('name', models.TextField()),
                ('marker', models.FileField(upload_to='')),
                ('routes', models.ManyToManyField(to='navigation.Route')),
            ],
        ),
    ]
